---
- name: Install packages for docker
  yum: 
    name: "{{ centos_packages_docker }}"
    state: latest 

- name: Add docker repo
  get_url:
    url: "{{ docker_repo }}"
    dest: "{{ path_docker_repo }}"
  
- name: Install docker
  shell:  |
    {{ docker_packages }}
  notify:
    - Statred and Enabled docker


